packages:
  - "apps/*"
  - "packages/*"
  - "packages/ui/*"
  - "tooling/*"

catalog:
  "@types/node": "^20.16.11"
  class-variance-authority: ^0.7.0
  eslint: ^9.13.0
  nativewind: ^4.1.23
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  react-native:
    react-native: ~0.76.1
    react-native-reanimated: ~3.16.1
