packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.13.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
  "@types/node": "^20.16.11"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
